### ISSUE TITLE
[Feat] 프로젝트 세팅

### ISSUE THREAD

**Issue by kkyu0718** [cmc-say-server/cmc-server#2]
## 📌  Feature Description
개발을 위한 디렉토리 생성 및 기본 파일 세팅

## 📝  To-do
- [ ] error 핸들러, error response dto 설정 
- [ ] response dto 설정
- [ ] 도메인 별 디렉토리 생성
